### ISSUE TITLE
Торговый терминал

### ISSUE THREAD

**Issue by Evhen-Dreval** [SBProX/Platform#161]
Ребята, добрый день, давно пользуюсь вашей платформой, только положительные эмоции и отзывы, спасибо!
скажите пожалуйста, планируете ли вы сделать реальный торговый терминал с подключением к онлайн котировкам?
спасибо!
dreval@bigmir.net

**Comment by SBProX** [comment]
Добрый день.

Таких планов на данный момент нет, и маловероятно что будет в ближайшее время.
Однако коннекторы для получения данных будут, это одна из приоритетных задач.
С помощью коннекторов можно будет смотреть любые инструменты, которые в нем будут. 
Это основная цель их подключения, но торговый функционал пока что не рассматривается в принципе.
