### ISSUE TITLE
Решено

### ISSUE THREAD

**Issue by Dimitrian** [SBProX/Platform#163]
Допустим имеем десять вкладок, все они по одному инструменту, но с разными таймфреймами и у каждой вкладки свой временной интервал. Так вот, при смене этого интервала на любой из вкладок, все другие вкладки автоматом меняют интервал на вновь заданный. 
В итоге ждешь когда загрузятся везде новые интервалы, потом все в ручную возвращаешь обратно, это боль.
Жду Ваши комментарии, а если так задумано специально, прошу разъяснить.

**Comment by SBProX** [comment]
У вас на этих вкладках включена линковка?

**Comment by SBProX** [comment]
> > У вас на этих вкладках включена линковка?
> 
> Как это выяснить?

Лучше сделаем так, оставьте здесь ваши контакты telegram, как только дойдут руки будем проверять эту проблему с вами свяжемся. Либо можете написать на @sbproofficial и оставить ваш контакт.

**Comment by Dimitrian** [comment]
Да, дело в линковке, совсем забыл о такой функции, я баран. Спасибо за подсказку. Пост удаляю.
