### ISSUE TITLE
Хотелось бы панель вкладок скрывать.

### ISSUE THREAD

**Issue by Torgovetsc** [SBProX/Platform#165]
Хотелось бы панель вкладок скрывать.

![image](https://user-images.githubusercontent.com/10338606/188085983-0f9a766c-6610-4ff0-b937-b22fc51192ca.png)

**Comment by SBProX** [comment]
Вкладки это обязательный элемент интерфейса, к которым привязан разный функционал.
Мы не будем делать скрытие вкладок.
