### ISSUE TITLE
Дублирование рисунков на графиках на разных ТФ

### ISSUE THREAD

**Issue by Janna-Janna** [SBProX/Platform#182]
**Опишите детально в чем должно заключаться улучшение, и если необходимо приложите изображения**
Добрый день. Прошу рассмотреть возможность улучшения платформы в виде дополнения функции дублировать рисунки. Это удобно при использовании разных ТФ по одному инструменту. 
Спасибо.
**Напишите контакты для связи (Email/Telegram/Skype) - это может потребоваться для уточнения деталей**
janna_min@mail.ru

**Comment by SBProX** [comment]
Добрый день.
Эта функция работает.
Если включить линковку, и в опциях линковки стоит опция инструментов рисования, то на линкованных графиках инструменты рисования будут дублироваться

**Comment by Janna-Janna** [comment]
> 
![линк](https://user-images.githubusercontent.com/63582167/191916551-9a297663-6389-4679-923c-b704314661ee.jpg)

Добрый день. Не копирует рисунки.
 Что делать?

**Comment by SBProX** [comment]
У вас старая версия.
Скачайте с сайте SBProX 7
