### ISSUE TITLE
Изменение часового пояса по отдельности в каждом графике.

### ISSUE THREAD

**Issue by Torgovetsc** [SBProX/Platform#210]
Прошу доработать функционал изменении часового пояса, что бы он привязывался к конкретному графику. Например мне нужно на 1D один часовой пояс, а на 1М другой. Это нужно для верного построения дневных свечей.
Спасибо.

**Comment by SBProX** [comment]
Увы но это не получится сделать, настройки пояса глобальны.
Если делать так как вы говорите, это придется все переписывать.
Чего бы делать не хотелось, тем более что запросов на такое изменение практически ни от кого не было.

**Comment by SBProX** [comment]
> Печаль. Просто мало кто анализирует дневные свечи, ну ладно. Но вдруг, не забывайте ))))

Хорошо)
