### ISSUE TITLE
Доработка горизонтальной дельты

### ISSUE THREAD

**Issue by 10Alexander10** [SBProX/Platform#212]
Хочу предложить доработать горизонтальную дельту, как индикатор, так и динамический профиль.(там тоже есть возможность включить дельту), а именно: выбор в фильтрах сделок с определённым лотом. К примеру выбрать в фильтре возможность показывать только крупные сделки 40-50 лотов, или же сделки совершённые лотностью 1-3. а чтоб сделки прошедшие с др лотностью игнорировались. Надеюсь понятна идея. Что то подобное есть в платформе multicharts. 
https://t.me/Alexander_Bekeshev        это моя телега.
моя почта    chif_bekeshev@mail.ru
Лучше конечно в телеге, или там и там.

**Comment by SBProX** [comment]
Идея понятна. В ранних версиях была такая функция.
Но потом ее убрали, потому что индикаторы приходилось отдельно считать из тиков.
Вам это кажется банальным, но на самом деле это сильно усложненная архитектура платформы получается.
Мы ее вообще убрали года 4 назад.

Делать этого не планируем.
