### ISSUE TITLE
Добавить фьючерс на NG (MOEX)

### ISSUE THREAD

**Issue by medoffngs** [SBProX/Platform#258]
Приветствую. Предлагаю добавить фьючерс на NG(MOEX), т.к. ликвидность(оборот) у этот фьючерса стала очень большой.

**Comment by kombik** [comment]
Этот инструмент уже просто необходим в системе

**Comment by AlexProfit73** [comment]
поддерживаю на 100%

**Comment by SBProX** [comment]
Мы не рассматриваем на GitHub подобные тикеты.
Что и как добавлять в плане инструментов решает руководство проекта.
