### ISSUE TITLE
Черный экран в 7 версии.

### ISSUE THREAD

**Issue by zaa3661** [SBProX/Platform#260]
Добрый день.
Много лет пользуюсь SBpro. До перехода на новые сервера использовал 6 версию на удаленном рабочем столе Win10 виртуальная машина VirtualBox 6.4.
Установил 7 версию. Она запускается и работает, но если отключиться от удаленно рабочего стола и снова подключиться получаем черный экран, то есть вроде как все работает, но графики на отображаются. 
Лечится только перезапуском приложения.
Шестая же версия продолжает работать стабильно.
Прошу решить данную ошибку. Или подсказать, что нужно настроить.
Скрин черного экрана.
[https://disk.yandex.ru/i/umKngI6X44rc3w](url)

**Comment by SBProX** [comment]
Вы можете использовать 8-ю версию платформы.
7-я уже обновляться не будет.
