### ISSUE TITLE
В SBProX8 некорректно работает рейтинг в идикаторе Clouds по суммированным принтам 

### ISSUE THREAD

**Issue by al10stash** [SBProX/Platform#268]
**Напишите контакты для связи (Email/Telegram/Skype) - это может потребоваться для уточнения деталей**

**Comment by al10stash** [comment]
![2023-04-16_10-25-47](https://user-images.githubusercontent.com/130886156/232286853-b2f86f9d-40ed-4c6d-9fa8-52443c880e77.png)

**Comment by al10stash** [comment]
email a[_stash@mail.ru

**Comment by al10stash** [comment]
al_stash@mail.ru

**Comment by al10stash** [comment]
Спасибо, понял что это не ошибка.

**Comment by SBProX** [comment]
Исправили рейтинг в 8.1.0.4
